version: '3.8'

services:
  ml-server:
    container_name: local-ml
    build: .             
    ports:
      - "5000:5000"
    volumes:
      # Mapping folder model di laptop ke dalam container
      # Format: ./folder_laptop : /folder_di_container
      - ./model:/app/model
    environment:
      - MODEL_PATH=/app/model/model_dnn(sigmoid).h5
    restart: unless-stopped