version: '3.8'

services:
  ml-server:
    container_name: local-ml
    build: .             
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model
    environment:
      - MODEL_PATH=/app/model/model_dnn300326.keras
      - MODEL_TINY_PATH=/app/model/model_dnntiny300326.tflite
    restart: unless-stopped